name: Lighthouse CI
on: [pull_request, workflow_dispatch]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          cache: yarn
          cache-dependency-path: lhci/yarn.lock
          registry-url: https://registry.npmjs.org/
          cache-path: ./yarn-cache
      - name: Install dependencies
        run: |
          cd lhci
          yarn install
      - name: Run Lighthouse CI
        run: |
          cd lhci
          yarn global add @lhci/cli@0.9.0
          lhci autorun --config=./lighthouserc.js
